daemon off;
worker_processes  1;

events {
    worker_connections 1024;
}
http {
    lua_code_cache off;
    lua_package_path "$prefix/services/?.lua;$prefix/package/?.lua;$prefix/utils/?.lua;;";

    server {
        listen 8080;
        access_log logs/access.log;
        error_log logs/error.log debug;

        location ^~ /api/ {
            access_by_lua_block {
                require("auth").go()
            }
        }

        location @proxy_to_frontend {
            proxy_pass http://localhost:3000;   # 后端服务地址
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Auth-Passed "true";
        }
    }
}