worker_processes  1;
error_log logs/error.log;
events {
    worker_connections 1024;
}
http {
    lua_package_path "$prefix/services/?.lua;$prefix/services/vendor/?.lua;;";
    server {
        listen 8080;
        location /api/ {
            default_type application/json;
            content_by_lua_block {
                require("auth").go()
            }
        }
    }
}